version: 1.0.{build}

branches:
  only:
  - master
#  - appveyor
  - appveyor-testbranch
  - appveyor-psx
  
skip_tags: true

image: Visual Studio 2017

configuration:
- Release

clone_folder: c:\projects\TOMB5

platform:
  - Win32
  
install:
  - set QTDIR=C:\Qt\5.7\mingw53_32
  - set C_INCLUDE_PATH=C:\psyq\include
  - set C_PLUS_INCLUDE_PATH=C:\psyq\include
  - set COMPILER_PATH=C:\psyq\bin
  - set G032TMP=C:\TEMP
  - set GO32=DPMISTACK 1000000
  - set LIBRARY_PATH=C:\psyq\lib
  - set PSX_PATH=C:\psyq\bin
  - set PSYQ_PATH=C:\psyq\bin
  - set TMPDIR=C:\TEMP
  - set PATH=%PATH%;C:\MinGW\bin;C:\psyq\bin;%QTDIR%\bin;%QTDIR%\Tools\mingw530_32\bin;
  - set PSYQ_SDK_URL="http://tomb5files.x10.mx/PSYQSDK.zip"
  - appveyor DownloadFile %PSYQ_SDK_URL% -FileName PSXSDK.zip
  - 7z x PSXSDK.zip -oC:\
  - set SDL2_URL="https://www.libsdl.org/release/SDL2-devel-2.0.7-VC.zip"
  - appveyor DownloadFile %SDL2_URL% -FileName SDL2.zip
  - 7z x SDL2.zip -oC:\projects\TOMB5\EXTERNAL\
  - set SDL2=C:\projects\TOMB5\EXTERNAL\SDL2-2.0.7
  
before_build:
  - cmd: mkdir C:\TEMP
  - cmd: icacls "C:\psyq" /grant Users:F
  - cmd: icacls "C:\TEMP" /grant Users:F
  - cmd: mingw32-make
  - cmd: md BUILD
  - cmd: cd BUILD
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 15 2017
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 15 2017 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DDART_MSVC_DEFAULT_OPTIONS="%MSVC_DEFAULT_OPTIONS%" ..

artifacts:
   - path: DISC\TOMB5.zip
     name: PSX_Binaries
   - path: BUILD\SPEC_PSXPC\*.zip
     name: PSXPC_Binaries

after_build:
   - cmd: cd SPEC_PSXPC
   - cmd: copy "C:\projects\TOMB5\EXTERNAL\SDL2-2.0.7\lib\x86\SDL2.dll" "%configuration%\"
   - 7z a DISC\TOMB5.zip "DISC\"
   - 7z a TOMB5.zip "%configuration%\"
  
#build: off