version: 1.0.{build}

branches:
  only:
  - master
#  - appveyor
  - appveyor-testbranch
  - test
  
skip_tags: true

configuration:
- Debug
- Release

clone_folder: c:\projects\TOMB5

build:
  project: c:\projects\TOMB5\BUILD\TOMB5.sln
  verbosity: minimal
  
platform:
  - Win32
  #- x64
  
install:
  - set QTDIR=C:\Qt\5.7\mingw53_32
  - set C_INCLUDE_PATH=C:\psyq\include
  - set C_PLUS_INCLUDE_PATH=C:\psyq\include
  - set COMPILER_PATH=C:\psyq\bin
  - set G032TMP=C:\TEMP
  - set GO32=DPMISTACK 1000000
  - set LIBRARY_PATH=C:\psyq\lib
  - set PSX_PATH=C:\psyq\bin
  - set PSYQ_PATH=C:\psyq\bin
  - set TMPDIR=C:\TEMP
  - set PATH=%PATH%;C:\MinGW\bin;C:\psyq\bin;%QTDIR%\bin;%QTDIR%\Tools\mingw530_32\bin;
  - set PSYQ_SDK_URL="http://psxdev.net/downloads/Psy-Q_46.zip"
  - appveyor DownloadFile %PSYQ_SDK_URL% -FileName PSXSDK.zip
  - 7z x PSXSDK.zip -oC:\
  
before_build:
  - cmd: move "c:\Psy-Q - 46" "c:\psyq"
  - cmd: icacls "C:\psyq" /grant Users:F
  - cmd: icacls "C:\TEMP" /grant Users:F
  - cmd: mingw32-make
  
artifacts:
   - path: DISC\*.zip
     name: Binaries
  
after_build:
  - cmd: cd SPEC_PSXPC
  - cmd: copy "C:\projects\TOMB5\EXTERNAL\SDL2-2.0.7\lib\x86\SDL2.dll" "%configuration%\"
  - 7z a TOMB5.zip "DISC\"
  
#build: off