version: 1.0.{build}

branches:
  only:
  - master
#  - appveyor
  - appveyor-testbranch
  - test
  
skip_tags: true

configuration:
- Debug
- Release

clone_folder: c:\projects\TOMB5

build:
  project: c:\projects\TOMB5\BUILD\TOMB5.sln
  verbosity: minimal
  
platform:
  - Win32
  #- x64
  
install:
  - set QTDIR=C:\Qt\5.7\mingw53_32
  - set PATH=%PATH%;C:\MinGW\bin;C:\psyq\bin;%QTDIR%\bin;%QTDIR%\Tools\mingw530_32\bin;
  - set PSYQ_SDK_URL="http://psxdev.net/downloads/Psy-Q_46.zip"
  - set PSPATHS_URL="http://www.psxdev.net/forum/download/file.php?id=537&sid=c734e74c4587111e3c739d592072c56a"
  - appveyor DownloadFile %PSYQ_SDK_URL% -FileName PSXSDK.zip
  - appveyor DownloadFile %PSPATHS_URL% -FileName pspath.reg
  - 7z x PSXSDK.zip -oC:\
  - cmd: regedit /S "pspath.reg"
  - cmd: move "c:\Psy-Q - 46" "c:\psyq"
  - cmd: icacls "C:\psyq" /grant Users:F
  
before_build:
  - cmd: mingw32-make
  
artifacts:
   - path: DISC\*.zip
     name: Binaries
  
after_build:
  - cmd: cd SPEC_PSXPC
  - cmd: copy "C:\projects\TOMB5\EXTERNAL\SDL2-2.0.7\lib\x86\SDL2.dll" "%configuration%\"
  - 7z a TOMB5.zip "DISC\"
  
#build: off