version: 1.0.{build}

branches:
  only:
  - master
#  - appveyor
  - appveyor-testbranch
  - test
  
skip_tags: true

image: Visual Studio 2017

configuration:
- Debug
- Release

clone_folder: c:\projects\TOMB5
#lib_folder: %clone_folder%\EXTERNAL

build:
  project: c:\projects\TOMB5\BUILD\TOMB5.sln
  verbosity: minimal
  
platform:
  - Win32
  #- x64
  
install:
  - set PATH=%PATH%;C:\MinGW\bin;C:\psyq\bin
  - set PSYQ_SDK_URL="http://psxdev.net/downloads/Psy-Q_46.zip"
  - set SDL2_URL="https://www.libsdl.org/release/SDL2-devel-2.0.7-VC.zip"
  - appveyor DownloadFile %SDL2_URL% -FileName SDL2.zip
  - appveyor DownloadFile %PSYQ_SDK_URL% -FileName PSXSDK.zip
  - 7z x SDL2.zip -oC:\projects\TOMB5\EXTERNAL\
  - 7z x PSXSDK.zip -oC:\psyq
  - set SDL2=C:\projects\TOMB5\EXTERNAL\SDL2-2.0.7
  
before_build:
  - cmd: cd %clone_folder%
  #- cmd: dir /s
  - cmd: mingw32-make
  - cmd: cd DISC
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 15 2017
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 15 2017 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DDART_MSVC_DEFAULT_OPTIONS="%MSVC_DEFAULT_OPTIONS%" ..
  
artifacts:
   - path: DISC\*.zip
     name: Binaries
  
after_build:
  - cmd: cd SPEC_PSXPC
  - cmd: copy "C:\projects\TOMB5\EXTERNAL\SDL2-2.0.7\lib\x86\SDL2.dll" "%configuration%\"
  - 7z a TOMB5.zip "%configuration%\"
  
#build: off
